export default {
  appContainerBgColor: '#fff',
  primaryAppColor: '#ff5722',
  primaryFontColor: 'white',
  footerBgColor: '#0d0d0d',
  copyRights: '#f2f2f2',
  black: 'black',
  white: 'white',
  blue: 'blue',
  linkBtnColor: '#337ab7',
  approvedAmtBgColor: '#5dc34b',
  paidAmtBgColor: 'green',
  pendingAmtBgColor: 'red',
  deniedAmtBgColor: 'red',
  gray: 'gray',
};
